### ISSUE TITLE
ProgressTracker swallows the request body's media type if it's a MimeBodyPublisher

### ISSUE THREAD

**Issue by XakepSDK** [mizosoft/methanol#46]
Can't upload multipart if ProgressTracker is used.
This happens only with big enough files.

Test code: https://github.com/XakepSDK/methanol-test/blob/master/src/main/java/dk/xakeps/methanoltest/Main.java

How to reproduce:
1. `git clone git@github.com:XakepSDK/methanol-test.git`
2. `cd methanol-test`
3. `mvn package`
4. `cd target`
5. Test without tracker: `java -jar methanol-test-1.0-SNAPSHOT.jar`
6. Test with tracker `java -jar methanol-test-1.0-SNAPSHOT.jar asdf`

When run with tracker, server fails to process request. Same happens with quarkus.

**Comment by mizosoft** [comment]
The problem seems to be that `ProgressTracker` swallows the body's media type (`MultipartBodyPublisher` implements `MimeBodyPublisher`), so no `Content-Type` is sent. Spark happens to complain when the request doesn't contain a multipart `Content-Type` when `getParts()` is called. You can notice that by registering an exception handler: 
```java
Spark.exception(Exception.class, (ex, req, res) -> ex.printStackTrace(System.out));
```

So, the test passes when adding:

```java
trackingPublisher = MoreBodyPublishers.ofMediaType(
    trackingPublisher, nonTrackingPublisher.mediaType());
```

However, this should be handled by `ProgressTracker` by returning a `MimeBodyPublisher` if the given one is such.

Thanks for reporting!
