### ISSUE TITLE
Release 1.7.0 not yet on Maven Central

### ISSUE THREAD

**Issue by ChristianCiach** [mizosoft/methanol#53]
Hi!

Let be begin this message by saying that I *love* methanol! For us, it is an essential library to make the java.net.HttpClient usable. We mainly use methanol so that read-timeouts work even when the Response is an `InputStream`. This is not possible with the vanilla HttpClient.

I just want to let you know that the latest release of methanol has not yet been published to Maven Central. I guess you probably already know about that, but I am writing this message just to make sure :)

Thanks again for your work!

**Comment by ChristianCiach** [comment]
Sorry, I was wrong! I was using https://mvnrepository.com/artifact/com.github.mizosoft.methanol/methanol to check for the current release, but this listing seems to be outdated. Methanol is listed on maven central directly: https://search.maven.org/search?q=g:com.github.mizosoft.methanol

**Comment by mizosoft** [comment]
Hi @ChristianCiach. Thank you for your kind words! Glad to hear you find Methanol useful! 

I believe that maven search engines take time to update their indices, particularly https://mvnrepository.com. The most important thing though is that the artifacts are visible in the [Maven Central repo](https://repo.maven.apache.org/maven2/com/github/mizosoft/methanol/), since this makes them consumable as dependencies (e.g. in gradle).
